### PR TITLE
Cloud init

### PR DESCRIPTION
**Pull request by midnightconman**

### CODE REVIEW

**Comment by docbobo** [comment]
@StefanScherer, I believe ```cloud-init``` is not yet integrate in the RPi version. Or is it? In the past, this was the main argument for not doing it for other variants either.

Once we had ```cloud-init```, we could also get rid of some scripts, like e.g. resizing the root fs, if I am not mistaken.

**Comment by StefanScherer** [comment]
Thanks @midnightconman this is a great idea.

@docbobo Correct, it is not yet integrated in the RPi version. Reasons are lack of time to do so and how we should do this breaking change. 
* Keeping device-init as a boot service but without the device-init.yaml so people used to device-init.yaml still could flash and use newer SD cards.
* Add a default user-data file for cloud-init with the standard user pirate + standard password
* Provide only a user-data.example file with password login, but suggest adding SSH pubkey. Having no user-data file will brick users not knowing the details. But would give more security but less convenience.

**Comment by midnightconman** [comment]
Thanks everyone... those are all very valid concerns.

What about a hybrid solution... maybe in device-init.yaml we can run `cloud-init init --force` or manually run cloud-init service `systemctl start cloud-init-local.service`? Then later when people start to adopt cloud-init phase out device-init and switch to pre-baked cloud-init files?

**Comment by StefanScherer** [comment]
Implemented with #32

**Pull request closed without merging**
