### PR TITLE
Initial ODROID-C2 support

### PR DESCRIPTION
**Pull request by umiddelb**
@DieterReuter you may be able to create a first image (which should boot at least). The stock kernel doesn't support Docker at this time. I've filed a [PR](https://github.com/hardkernel/linux/pull/159) to fix this.

Cheers
Uli

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thanks! I've restarted Travis due to another httpredir.debian.org issue.

**Comment by StefanScherer** [comment]
Still got this

```
W: Failed to fetch https://packagecloud.io/Hypriot/Schatzkiste/debian/dists/wheezy/InRelease  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)
W: Failed to fetch http://deb.odroid.in/dists/xenial/main/binary-arm64/Packages  404  Not Found
```

OK, Schatzkiste must be filled with arm64 treasure.
But the xenial?

**Comment by StefanScherer** [comment]
But we can skip the docker tools for the moment, merge and work on in in other PR's. No problem.

**Comment by umiddelb** [comment]
> But the xenial?

Its the repository which provides the kernel package for the ODROID-C2 at this time. You may skip

```
deb http://deb.odroid.in/ xenial main
```

but keep

```
deb http://deb.odroid.in/c2/ xenial main
```

**Pull request merged**
