### PR TITLE
Initial draft for init_resize

### PR DESCRIPTION
**Pull request by bspeice**
Intended to address #33.
I don't have the ability to test this at the moment because my C2 is in use, but @trebolcinco, are you able to test this?

### CODE REVIEW

**Comment by trebolcinco** [comment]
@bspeice i am traveling until Friday, will start on this by Saturday.  Mike

**Comment by bspeice** [comment]
Excellent. Let me know if you need any assistance in getting the test set up.

**Comment by bspeice** [comment]
I've got another C2 in the mail, I'll take a look at this again once it arrives.

**Comment by trebolcinco** [comment]
Apologies been battling a few things but am now available to take a whack at it.

**Comment by trebolcinco** [comment]
When I run "make docker-machine" it hangs at "Installing Docker" . The host machine is a mac, not sure if that is an issue or not.  I do see the makefile mapping /boot which isn't present of course on macos.

**Comment by bspeice** [comment]
I'm actually not using the `make docker-machine` step in testing - using the host's `docker` installation is totally fine, the `docker-machine` part is only really useful if you can't install `docker` onto the host.

**Comment by bspeice** [comment]
Confirmed that this is definitely not working initially. It's going to take some time, but I think I need to do some work to make a more robust script.

**Comment by bspeice** [comment]
Tested as working for me. Wouldn't mind having someone else check on this, but looking pretty good:
```
pirate@192.168.1.101's password: 
Linux black-pearl 3.14.79-117 #1 SMP PREEMPT Tue Jan 2 23:46:30 BRST 2018 aarch64

HypriotOS (Debian GNU/Linux 9)

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
HypriotOS/arm64: pirate@black-pearl in ~
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            717M     0  717M   0% /dev
tmpfs           172M  6.7M  166M   4% /run                                                                                           
/dev/mmcblk0p2   28G  668M   27G   3% /                                                                                              
tmpfs           859M     0  859M   0% /dev/shm                                                                                       
tmpfs           5.0M     0  5.0M   0% /run/lock                                                                                      
tmpfs           859M     0  859M   0% /sys/fs/cgroup                                                                                 
/dev/mmcblk0p1   64M   42M   23M  66% /boot                                                                                          
tmpfs           172M     0  172M   0% /run/user/1000  
```

Note that it will shutdown on first boot (which resizes the partition) and will be fine afterward (second boot resizes the fs).

**Comment by bspeice** [comment]
Don't merge quite yet - I want to try some things with `partprobe` to see if I can do this all in one step. I'll update the issue if that fails.

**Comment by bspeice** [comment]
Alright, this is now working without reboots. Don't know that anything else is needed.

**Comment by trebolcinco** [comment]
@bspeice I can test if you have an image I can pull.

**Comment by bspeice** [comment]
It's a bit difficult to get a 1GB image somewhere. Do you have a preference on how to receive it? Otherwise, my recommendation would be to publish a Git repository with it as the single file.

**Comment by trebolcinco** [comment]
@bspeice that sounds fine to me.  Is there anyway for me to build it on my own on a Mac?

**Comment by bspeice** [comment]
`make sd-image` should be sufficient as long as Docker is installed, no need for using the Vagrant box. I'll get the file uploaded now, will comment once it's prepared.

**Comment by bspeice** [comment]
Turns out Github has a 100MB file limit. I've instead hosted the file on a [personal Git server](https://git.speice.io/bspeice/test-odroid-image). Let me know when you've downloaded the file, as I'd rather not leave this up indefinitely.

**Comment by trebolcinco** [comment]
All set… am testing now.  You can hide or remove you repo.

Thanks!

**Comment by StefanScherer** [comment]
@bspeice You can use GitHub releases for that, no 100MB limit there.

**Comment by trebolcinco** [comment]
So far so good... burned two sizes,  64 and 32 and they resized without problem.

Mike Taylor
+1 415 255 1099 h
+1 415 320 8360 c
mx 152-5403 / 109-2282
mt@miketaylor.net iMessage

**Comment by bspeice** [comment]
Glad to hear. Any concerns in recommending this to @StefanScherer for merge?

**Comment by StefanScherer** [comment]
@bspeice and @trebolcinco thanks for this PR and testing it.
LGTM

**Comment by StefanScherer** [comment]
I'll merge and release a 0.4.1 version.

**Comment by trebolcinco** [comment]
Thanks, still working fine and good to go imho

**Pull request merged**
